documentation:
  - changed-files:
      - any-glob-to-any-file: "**/*.md"

ci:
  - changed-files:
      - any-glob-to-any-file: ".github/**"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "**/go.mod"
          - "**/go.sum"

go:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.go"
          - "**/go.mod"

docker:
  - changed-files:
      - any-glob-to-any-file:
          - "**/Dockerfile*"
          - "**/docker-compose*"
          - "compose*"
